# _config.yml

title: "tclBlend2 - Gallery"

#baseurl: /tclBlend2d-Gallery
baseurl: xxGallery


collections:
  cards:
    output: true

plugins:
  - jekyll-paginate-v2

# ======================================================
# pagination - v2
# ======================================================

pagination:
   enabled: true
   per_page: 15

defaults:
  - scope:
      path: ""
      type: "cards"
    values:
      layout: "card"
  - scope:
      path: ""
    values:
      layout: "default"

